name: Build and deploy master

on:
  workflow_run:
    
  push:
    branches: [master]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    name: Build and deploy main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/node_modules
          key: cache-${{ hashFiles('**/package-lock.json') }}

      # pass --base for application to work under GitHub pages
      - name: Install and build
        run: |
          npm install
          npm run build -- --base=/${{ github.event.repository.name }}/
      - name: Publish deployed code 
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          name: published
          path: dist
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.3
        with:
           token: ${{ github.token }}
    # Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes
    # Name of the artifact to deploy
           artifact_name: published
      
